# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pantry-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pantry-app
  pod 'MVVMKit', '2.2.1'
  pod 'SnapKit', '~> 5.6.0'
end
